name: CI
on: [ push, pull_request ]

jobs:

  validate_fly_io_config_file:
    name: Validate fly.io config file
    runs-on: ubuntu-latest

    env:
      # For validation, we need for some reason the API token
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup fly.io CLI tool
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Validate fly.io config file
        run: flyctl config validate

  deploy:
    name: Deploy app
    needs: validate_fly_io_config_file
    runs-on: ubuntu-latest

    # Run only on pushing to main
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup fly.io CLI tool
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to fly.io
        run: flyctl deploy --remote-only
